# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://air-control-training-squadron.github.io/"

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: "/acts-site"